### ISSUE TITLE
Suggestion: Rename to Socket.lean

### ISSUE THREAD

**Issue by Anderssorby** [xubaiw/Socket.lean#5]
I suggest renaming the library to Socket.lean. I think it is a simple and intuitive naming scheme to use the name of the top level module as the name of the project.

**Comment by xubaiw** [comment]
The current name lead to sone problem?
Many of lean projects follow the hyphen scheme, and it's also the default scheme of GitHub.

**Comment by Anderssorby** [comment]
No problems, but I like Socket.lean better. It signifies that there can be no name collisions in the top level module. I started using this scheme in yatima-inc with things like https://github.com/yatima-inc/OpenSSL.lean (which started with the hyphen scheme) or https://github.com/Anderssorby/SDL.lean

**Comment by xubaiw** [comment]
Renamed
